apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "avstein@hotmail.de"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector: {}
      - http01:
          ingress:
            class: nginx